# Generated by Django 3.2.6 on 2021-08-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plink_case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validparametres',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='validparametres',
            name='ipaddress',
        ),
        migrations.RemoveField(
            model_name='validparametres',
            name='last_name',
        ),
    ]
