# Generated by Django 3.2.6 on 2021-08-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plink_case', '0002_auto_20210815_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidParametres',
        ),
    ]
