# Generated by Django 3.2.6 on 2021-08-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plink_case', '0004_validparametres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidParametres',
        ),
    ]
