# Generated by Django 3.2.6 on 2021-08-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plink_case', '0006_validparametres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidParametres',
        ),
    ]
