# Generated by Django 3.2.6 on 2021-08-15 20:41

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plink_case', '0008_validparametres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validparametres',
            name='password',
            field=models.CharField(max_length=16, validators=[django.contrib.auth.password_validation.validate_password]),
        ),
    ]
