# Generated by Django 3.2.6 on 2021-08-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plink_case', '0010_alter_validparametres_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validparametres',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
